name: remote server deployment
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploying the latest update
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        port: 22
        script: . /home/${{ secrets.USERNAME }}/bots/deploy-hawkeye.sh